//////////////////////////////////////////
// Common Radius variables
//////////////////////////////////////////

@description('Information about what resource is calling this Recipe. Generated by Radius.')
param context object
var resourceName = '${context.resource.name}-mysql-${uniqueString(context.resource.id, resourceGroup().id)}'
var applicationName = context.application != null ? context.application.name : ''
var environmentName = context.environment != null ? context.environment.name : ''
var resourceGroupName = split(context.resource.id, '/')[5]
var location string = resourceGroup().location

//////////////////////////////////////////
// MySQL variables
//////////////////////////////////////////

var dbSecretName = context.resource.properties.secretName

// Reconstruct the Radius.Security/secrets resource ID from this resource's own ID, since both
// share the same resource group path prefix and the secretName property is only a plain name.
var secretResourceId = replace(
  context.resource.id,
  'Radius.Data/mySqlDatabases/${context.resource.name}',
  'Radius.Security/secrets/${dbSecretName}'
)

// Must match the vault naming scheme used by the azure-key-vault-secrets.bicep secrets Recipe.
var vaultName = take('${dbSecretName}-kv-${uniqueString(secretResourceId, resourceGroup().id)}', 24)

resource vault 'Microsoft.KeyVault/vaults@2026-02-01' existing = {
  name: vaultName
}

// The underlying Microsoft.DBforMySQL/flexibleServers administratorLogin property is a plain
// (non-secure) string, and Bicep's getSecret() can only be assigned directly to a @secure()
// module parameter. To still source the login name from Key Vault, a deployment script reads the
// USERNAME secret at deployment time via the Azure CLI and exposes it as a plain-string output.
resource scriptIdentity 'Microsoft.ManagedIdentity/userAssignedIdentities@2023-01-31' = {
  name: '${resourceName}-script-identity'
  location: location
}

// Key Vault Secrets User: built-in role granting data-plane 'get'/'list' access to secrets.
var keyVaultSecretsUserRoleId = '4633458b-17de-408a-b874-0445c86b69e6'

// The vault uses RBAC authorization (see azure-key-vault-secrets.bicep), so the script identity
// needs a role assignment scoped to the vault rather than an access policy entry.
resource vaultSecretsUserRoleAssignment 'Microsoft.Authorization/roleAssignments@2022-04-01' = {
  name: guid(vault.id, scriptIdentity.id, keyVaultSecretsUserRoleId)
  scope: vault
  properties: {
    roleDefinitionId: subscriptionResourceId('Microsoft.Authorization/roleDefinitions', keyVaultSecretsUserRoleId)
    principalId: scriptIdentity.properties.principalId
    principalType: 'ServicePrincipal'
  }
}

resource getUsernameScript 'Microsoft.Resources/deploymentScripts@2023-08-01' = {
  name: '${resourceName}-get-username'
  location: location
  kind: 'AzureCLI'
  identity: {
    type: 'UserAssigned'
    userAssignedIdentities: {
      '${scriptIdentity.id}': {}
    }
  }
  properties: {
    azCliVersion: '2.62.0'
    retentionInterval: 'PT1H'
    timeout: 'PT5M'
    cleanupPreference: 'OnSuccess'
    environmentVariables: [
      {
        name: 'VAULT_NAME'
        value: vaultName
      }
    ]
    scriptContent: '''
      set -e
      username=$(az keyvault secret show --vault-name "$VAULT_NAME" --name USERNAME --query value -o tsv)
      echo "{\"username\":\"$username\"}" > "$AZ_SCRIPTS_OUTPUT_PATH"
    '''
  }
  dependsOn: [
    vaultSecretsUserRoleAssignment
  ]
}

var database = context.resource.properties.?database ?? 'mysql_db'

@description('The major MySQL server version in the X.Y format. Defaults to the version 8.4 if not provided.')
@allowed([
  '5.7'
  '8.0'
  '8.4'
])
param version string = context.resource.properties.?version ?? '8.4'

// Maps the allowed input versions to the exact version literals accepted by the AVM module for DBforMySQL Flexible Server.
var mysqlVersionMap = {
  '5.7': '5.7'
  '8.0': '8.0.21'
  '8.4': '8.4'
}

var port = 3306

// Radius labels to be applied as Azure resource tags. The dash in the resource type is replaced with a hyphen to conform to Azure tag naming rules.
var labels = {
  'radapp.io-resource': resourceName
  'radapp.io-application': applicationName
  'radapp.io-environment': environmentName
  'radapp.io-resource-type': replace(context.resource.type, '/', '-')
  'radapp.io-resource-group': resourceGroupName
}

//////////////////////////////////////////
// MySQL Deployment
//////////////////////////////////////////

// Using the AVM module for DBforMySQL Flexible Server to deploy a MySQL server in Azure
module flexibleServer 'br/public:avm/res/db-for-my-sql/flexible-server:0.10.3' = {
  params: {
    // Required parameters
    availabilityZone: -1
    name: resourceName
    skuName: 'Standard_B1ms'
    tier: 'Burstable'
    // Non-required parameters
    tags: labels
    location: location
    administratorLogin: getUsernameScript.properties.outputs.username
    administratorLoginPassword: vault.getSecret('PASSWORD')
    storageAutoIoScaling: 'Enabled'
    storageSizeGB: 32
    version: mysqlVersionMap[version]
    publicNetworkAccess: 'Enabled'
    highAvailability: 'Disabled'
    databases: [
      {
        name: database
        charset: 'utf8'
        collation: 'utf8_general_ci'
      }
    ]
  }
}

//////////////////////////////////////////
// Output Radius result
//////////////////////////////////////////

output result object = {
  values: {
    host: flexibleServer.outputs.fqdn
    port: port
    database: database
  }
}
