//////////////////////////////////////////
// Common Radius variables
//////////////////////////////////////////

@description('Information about what resource is calling this Recipe. Generated by Radius.')
param context object

var applicationName = context.application != null ? context.application.name : ''
var environmentName = context.environment != null ? context.environment.name : ''
var resourceGroupName = split(context.resource.id, '/')[5]
var location string = resourceGroup().location

// Key Vault names must be globally unique and no longer than 24 characters.
var vaultName = take('${context.resource.name}-kv-${uniqueString(context.resource.id, resourceGroup().id)}', 24)

// Radius labels to be applied as Azure resource tags. The dash in the resource type is replaced with a hyphen to conform to Azure tag naming rules.
var labels = {
  'radapp.io-resource': context.resource.name
  'radapp.io-application': applicationName
  'radapp.io-environment': environmentName
  'radapp.io-resource-type': replace(context.resource.type, '/', '-')
  'radapp.io-resource-group': resourceGroupName
}

//////////////////////////////////////////
// Secret variables
//////////////////////////////////////////

var secretData = context.resource.properties.data

// Key Vault secrets are plain strings, so base64-encoded values must be decoded before storage.
var secrets = [
  for item in items(secretData): {
    name: item.key
    value: (item.value.?encoding ?? 'string') == 'base64' ? base64ToString(item.value.value) : item.value.value
  }
]

//////////////////////////////////////////
// Key Vault Deployment
//////////////////////////////////////////

// Using the AVM module for Key Vault to store secret values from the Radius.Security/secrets Resource Type.
module vault 'br/public:avm/res/key-vault/vault:0.13.0' = {
  params: {
    // Required parameters
    name: vaultName
    // Non-required parameters
    location: location
    tags: labels
    sku: 'standard'
    // RBAC is used instead of access policies. The identity Radius uses to deploy Azure Recipes is
    // expected to be pre-provisioned with a role granting secrets access (e.g. Key Vault Secrets
    // Officer) at the resource group scope Radius deploys into, so it applies automatically here.
    enableRbacAuthorization: true
    enablePurgeProtection: false
    enableTelemetry: false // This is to disable telemetry for the Key Vault module, as otherwise it fails to deploy in some regions due to telemetry being unavailable.
    secrets: secrets
  }
}

//////////////////////////////////////////
// Output Radius result
//////////////////////////////////////////

output result object = {
  resources: [
    vault.outputs.resourceId
  ]
}
